version: '3.9'

services:
  postgres:
    image: 'postgres:14-alpine'
    environment:
      - 'POSTGRES_DB=amazing-pc-db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'