spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/amazing-pc-db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#      ddl-auto: create
#      ddl-auto: validate
#    show-sql: true
  flyway:
#    locations: classpath:db.migration
#    url: jdbc:postgresql://localhost:5433/amazing-pc-db
#    user: postgres
#    password: postgres
    baseline-on-migrate: true
    enabled: false

jwt:
  secret:
    key: "439adb87583df62d6ef6ba54faf42945c9ca704f7069f975898d1f7210ad05f6"
  expiration: 24h