spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/amazing-pc-db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration